    $(document).ready(function(){
		
    $(".log-bu").click(function(){
		$(".main-log-1").show();
        $(".main-log-1").addClass("down-move");
		$(".main-log-2").removeClass("up-move").hide();
		$(".main-log-3").removeClass("up-move").hide();
		$(".main-log-4").removeClass("up-move").hide();
    });
	$(".q-text").click(function(){
        $(".main-log-1").hide();
		$(".main-log-2").show();
    });
    $(".close-1").click(function(){
        $(".main-log-1").removeClass("down-move");
    });	
	$(".arrow-1").click(function(){
        $(".main-log-2").hide();
		$(".main-log-1").show();
    });
	$(".log-tip-1").click(function(){
		$(".log-2-pup").fadeIn(800);
    });
	$(".log-2-pup").click(function(){
		$(".log-2-pup").fadeOut(800);
    });
	$(".close-2").click(function(){
		$(".main-log-1").show().removeClass("down-move");
        $(".main-log-2").addClass("up-move");
    });
	$(".close-3").click(function(){
		$(".main-log-1").show().removeClass("down-move");
        $(".main-log-3").addClass("up-move");
    });
	$(".ok-bu-1").click(function(){
        $(".main-log-2").hide();
		$(".main-log-3").show();
    });
	$(".arrow-2").click(function(){
        $(".main-log-3").hide();
		$(".main-log-2").show();
    });
	$(".log-tip-2").click(function(){
		$(".log-3-pup").fadeIn(800);
    });
	$(".log-3-pup").click(function(){
		$(".log-3-pup").fadeOut(800);
    });
    $(".close-4").click(function(){
        $(".main-log-1").show().removeClass("down-move");
		$(".main-log-4").addClass("up-move");
    });	
	$(".ok-bu-2").click(function(){
        $(".main-log-3").hide();
		$(".main-log-4").show();
    });
	$(".arrow-3").click(function(){
        $(".main-log-4").hide();
		$(".main-log-3").show();
    });
    $(".ok-bu-3").click(function(){
        $(".main-log-1").show().removeClass("down-move");
		$(".main-log-4").fadeOut(500);
    });	


    $(".reg-bu").click(function(){
		$(".main-reg-1").show();
        $(".main-reg-1").addClass("down-move");
		$(".main-reg-2").removeClass("up-move").hide();
		$(".main-reg-3").removeClass("up-move").hide();
    });
    $(".close-5").click(function(){
        $(".main-reg-1").removeClass("down-move");
    });
	$(".reg-tip-1").click(function(){
		$(".reg-1-pup").fadeIn(800);
    });
	$(".reg-1-pup").click(function(){
		$(".reg-1-pup").fadeOut(800);
    });
	$(".ok-bu-4").click(function(){
        $(".main-reg-1").hide();
		$(".main-reg-2").show();
    });
	$(".arrow").click(function(){
        $(".main-reg-2").hide();
		$(".main-reg-1").show();
    });
    $(".close-6").click(function(){
        $(".main-reg-1").show().removeClass("down-move");
		$(".main-reg-2").addClass("up-move");
    });
	$(".reg-tip-2").click(function(){
		$(".reg-2-pup").fadeIn(800);
    });
	$(".reg-2-pup").click(function(){
		$(".reg-2-pup").fadeOut(800);
    });
	$(".ok-bu-5").click(function(){
        $(".main-reg-2").hide();
		$(".main-reg-3").show();
    });
	
    $(".other-log-bu").click(function(){
		$(".main-other-1").addClass("down-move");
    });
    $(".close-7").click(function(){
        $(".main-other-1").removeClass("down-move");
    });
	$(".other-tip-1").click(function(){
		$(".reg-1-pup").fadeIn(800);
    });
	$(".reg-1-pup").click(function(){
		$(".reg-1-pup").fadeOut(800);
    });
    });	