    $(document).ready(function(){
		
    $(".tab-bar-1").click(function(){
        $(".report-page").addClass("down-move");
		$(".tab-bar-1").hide();
		$(".tab-bar-1-hover").show();
    });
    $(".close-1,.tab-bar-1-hover,.tab-bar-2,.tab-bar-3,.tab-bar-4").click(function(){
        $(".report-page").removeClass("down-move");
		$(".tab-bar-1").show();
		$(".tab-bar-1-hover").hide();
		$(".report-detail").hide();
    });
    $(".list-bu-1").click(function(){
		$(".report-pup").fadeIn(800);
    });
    $(".report-pup").click(function(){
		$(".report-pup").fadeOut(800);
    });
    $(".report-name").click(function(){
		$(".report-detail").show();
    });	
    $(".arrow-1").click(function(){
		$(".report-detail").hide();
    });		
    $(".date-1").click(function(){
		$(".calendar-1").show();
		$(".date-1").hide();
		$(".date-1-hover").show();
    });
	$(".date-1-hover,.calendar-1").click(function(){
		$(".calendar-1").hide();
		$(".date-1").show();
		$(".date-1-hover").hide();
    });
    $(".date-2").click(function(){
		$(".calendar-2").show();
		$(".date-2").hide();
		$(".date-2-hover").show();
    });
	$(".date-2-hover,.calendar-2").click(function(){
		$(".calendar-2").hide();
		$(".date-2").show();
		$(".date-2-hover").hide();
    });
    $(".condition").click(function(){
		$(".condition-window").show();
		$(".condition").hide();
		$(".condition-hover").show();
    });
	$(".condition-hover,.condition-window").click(function(){
		$(".condition-window").hide();
		$(".condition").show();
		$(".condition-hover").hide();
    });

    $(".tab-bar-2").click(function(){
        $(".search-page").addClass("down-move");
		$(".tab-bar-2").hide();
		$(".tab-bar-2-hover").show();
    });
    $(".close-2,.tab-bar-1,.tab-bar-2-hover,.tab-bar-3,.tab-bar-4").click(function(){
        $(".search-page").removeClass("down-move");
		$(".tab-bar-2").show();
		$(".tab-bar-2-hover").hide();
		$(".search-detail").hide();
    });
    $(".list-bu-2").click(function(){
		$(".search-pup").fadeIn(800);
    });
    $(".search-pup").click(function(){
		$(".search-pup").fadeOut(800);
    });
    $(".search-kind-bu").click(function(){
		$(".search-kind").show();
		$(".search-kind-bu").hide();
		$(".search-kind-bu-hover").show();
    });
    $(".search-kind-bu-hover").click(function(){
		$(".search-kind").hide();
		$(".search-kind-bu").show();
		$(".search-kind-bu-hover").hide();
    });
    $(".search-name").click(function(){
		$(".search-detail").show();
    });	
    $(".arrow-2").click(function(){
		$(".search-detail").hide();
    });
		
    $(".tab-bar-3").click(function(){
        $(".notice-page").addClass("down-move");
		$(".tab-bar-3").hide();
		$(".tab-bar-3-hover").show();
    });
    $(".close-3,.tab-bar-1,.tab-bar-2,.tab-bar-3-hover,.tab-bar-4").click(function(){
        $(".notice-page").removeClass("down-move");
		$(".notice-detail").hide();
		$(".tab-bar-3").show();
		$(".tab-bar-3-hover").hide();
    });
    $(".notice-name").click(function(){
		$(".notice-detail").show();
    });	
    $(".arrow-3").click(function(){
		$(".notice-detail").hide();
    });
		
    $(".tab-bar-4").click(function(){
        $(".buy-page").addClass("down-move");
		$(".tab-bar-4").hide();
		$(".tab-bar-4-hover").show();
    });
    $(".close-4,.tab-bar-1,.tab-bar-2,.tab-bar-3,.tab-bar-4-hover").click(function(){
        $(".buy-page").removeClass("down-move");
		$(".buy-detail").hide();
		$(".tab-bar-4").show();
		$(".tab-bar-4-hover").hide();
    });
    $(".buy-bu").click(function(){
		$(".buy-detail").show();
    });
    $(".arrow-4").click(function(){
		$(".buy-detail").hide();
    });
	
    $(".page-my-tip").click(function(){
		$(".page-my-tip").fadeOut(800);
    });
    $(".page-my-bu-arrow").click(function(){
		$(".page-my-bu-container").toggleClass("right-move page-my-bu-bg");
    });
    $(".page-my-bu-set,.set-bu").click(function(){
        $(".set-page").addClass("down-move");
    });
    $(".close-5,.page-my-set-bu").click(function(){
        $(".set-page").removeClass("down-move");
    });
    $(".page-my-bu-price").click(function(){
        $(".price-page").addClass("down-move");
    });
    $(".close-6").click(function(){
        $(".price-page").removeClass("down-move");
    });
	
    $(".page-choice").click(function(){
        $(".page-choice-bar").addClass("page-choice-right-move");
		$(".pup-window-bg").fadeIn(800);	
    });
    $(".pup-window-bg").click(function(){
        $(".page-choice-bar").removeClass("page-choice-right-move");
		$(".pup-window-bg").fadeOut(800);	
    });
	
    $(".delete-bu,.page-my-bu-remove").click(function(){
		$(".stock-detail-pup").fadeIn(800);
    });
    $(".stock-detail-pup").click(function(){
		$(".stock-detail-pup").fadeOut(800);
    });
				
    });	